stemstr/Client

components/ApplicationContainer/ApplicationContainer.js
components/Fields/CommentField/CommentField.js
components/Fields/SoundPicker/SoundPicker.js
components/FileDropOverlay/FileDropOverlay.js
components/PostSheet/PostSheet.js
components/RepostButton/RepostButton.js
components/SoundPlayer/SoundPlayer.js
components/WaveForm/WaveForm.js
nostr/hooks/useHomeFeed.tsx
nostr/hooks/useProfileFeed.tsx
package.json
pages/user/[hexOrNpub].js
yarn.lock

- Implement new upload protocol
- Add kind 1808 streaming notes
- Add real waveforms
- Add drag & drop of audio files into app

New upload protocol, streaming (kind 1808), drag&drop

---

components/BottomNavigation/BottomNavigation.js
components/HomeFeedHeader/HomeFeedHeader.js
components/Note/Note.js

Remove unimplemented buttons

---

pages/_app.tsx
pages/index.tsx

feat: add og tags

---

components/Fields/SoundPicker/SoundPicker.js

Fix "sum does not match content" bug

Upload bug fix

---

pages/login.js

fix: only show extension login if present

---

components/Fields/CommentField/CommentField.js
components/Fields/SoundPicker/SoundPicker.js
components/FileDropOverlay/FileDropOverlay.js
components/PostSheet/PostSheet.js
components/SoundPlayer/SoundPlayer.js
theme/Theme.tsx
utils/media.ts

Share sheet polish

---

nostr/hooks/useProfile.tsx
store/Auth.ts

Don't overwrite profile metadata unless newer

---

nostr/hooks/index.ts
nostr/index.ts

resolves https://github.com/stemstr/Client/issues/52

consolidate exports for nostr dir

---

components/DownloadSoundButton/DownloadSoundButton.js
components/Note/Note.js
hooks/useFeatureDetection.tsx
package.json
yarn.lock

- Add useFeatureDetection hook
- Disable drag to download if unsupported

Add feature detection for drag to download

---

nostr/utils.ts

fix: short-hand relative time

---

components/ApplicationContainer/ApplicationContainer.tsx
components/BackButton/BackButton.js
components/BottomNavigation/BottomNavigation.tsx
components/FileDropOverlay/FileDropOverlay.js
components/HomeFeed/HomeFeed.js
components/HomeFeedHeader/HomeFeedHeader.js
components/Note/Note.js
components/Note/Note.styles.js
components/NoteAction/NoteAction.js
components/NoteAction/NoteActionComment.js
components/NoteHeader/NoteHeader.js
components/NoteTags/NoteTags.js
components/PostSheet/PostSheet.js
components/ProfileFeed/ProfileFeed.js
components/SoundPlayer/SoundPlayer.js
enums/routes.ts
nostr/hooks/index.ts
nostr/hooks/useProfile.tsx
nostr/hooks/useThread.tsx
nostr/utils.ts
pages/_app.tsx
pages/index.tsx
pages/signup.js
pages/thread/[noteId].js
pages/user/[hexOrNpub].js
store/Sheets.ts
utils/hoc/withStopClickPropagation.js

- add thread view
- add reply feature

Add thread view/commenting

---

components/HomeFeed/HomeFeed.js
components/NoteAction/NoteActionComment.js
pages/index.tsx

- don't show 0 reply count
- fix scrolling issues

Thread improvements

---

components/BackButton/BackButton.tsx
components/ProfileActionButton/ProfileActionButton.tsx
pages/_app.tsx
pages/index.tsx
pages/user/[hexOrNpub].tsx
tsconfig.json

* Fixes Profile view side scrolling as previously `margin-left` and `margin-right` were making the screens wider than they should be. Added a media breakpoint to remove them on smaller screens.
* Converted Components involved into TS: `BackButton`, `ProfileActionButton`, `[hexOrNpub]` page.
* `userData?.pk?` doesn't exist only `pk` exists

fix: Fix Profile view side scrolling

---

components/NoteHeader/NoteHeader.js

this completes the first task of https://github.com/stemstr/Client/issues/22

navigate to profile on name tap

---

components/Note/Note.js
components/NoteHeader/NoteHeader.js
components/NoteTags/NoteTags.js

this completes the 2nd task of https://github.com/stemstr/Client/issues/22

make note header responsive

---

.gitignore
components/ApplicationContainer/ApplicationContainer.tsx
components/HomeFeed/HomeFeed.js
ndk/NDKProvider.tsx
package.json
pages/index.tsx
yarn.lock

resolves https://github.com/stemstr/Client/issues/55

virtualize feed

---

components/Feed/Feed.tsx
components/HomeFeed/HomeFeed.tsx
ndk/hooks/useFeedWithEose.ts
ndk/hooks/useHomeFeed.tsx
ndk/hooks/useHomeFeedPubkeys.ts
ndk/hooks/usePreloadProfileCache.ts
ndk/hooks/useUser.tsx
ndk/inMemoryCacheAdapter.ts
ndk/utils.tsx
utils/common.ts

@michaelhall923 let me know if this gets rid of the flickering for you on the home feed.
- preload profiles for first 20 events in feed before rendering feed
- wait for eose before rendering initial feed
- render cached user data in note headers on first render

Improve initial feed loading

---

pages/login.tsx

link to discover feed from login page

---

components/PostSheet/PostSheet.js

change "share" button to "reply" on reply sheet

---

components/Note/Note.js
components/NoteAction/NoteActionComment.tsx
components/PostSheet/PostSheet.js
ndk/hooks/useUser.tsx
store/Sheets.ts

resolves https://github.com/stemstr/Client/issues/99

fix missing reply name

---

components/NoteTags/NoteTags.js

wrap note tags

---

components/NoteTags/NoteTags.js

make note tags scrollable on small screens

---

ndk/utils.tsx

fix comments not working

---

components/Feed/Feed.tsx
components/Note/Note.js
components/NoteContent/MentionLink.tsx
components/NoteContent/NoteContent.tsx
constants/nostr.ts
ndk/utils.tsx
pages/_app.tsx

resolves https://github.com/stemstr/Client/issues/133

display mentions as a link

---

components/ZapWizard/InvoiceDrawer.tsx
package.json
tsconfig.json
webln-types.d.ts
yarn.lock

now if you have an ext that supports webln e.g. Alby, the Pay with wallet button is displayed and when you click it, it attempts to pay with webln.

add webln support

---

components/ContactsTray/ContactsTray.tsx
components/ContactsTray/FollowingPanel.tsx
components/ContactsTray/UserFeed.tsx
components/FollowButton/FollowButton.tsx
components/ProfilePage/ProfileContactsBar.tsx
ndk/hooks/useContactList.tsx
ndk/inMemoryCacheAdapter.ts
ndk/utils.tsx

Cache contact lists

---

components/NoteAction/NoteActionLike.tsx

resolves https://github.com/stemstr/Client/issues/132

prevent multiple likes on a note

---

components/Note/Note.styles.js
components/SoundPlayer/SoundPlayer.styles.js
components/SoundPlayer/SoundPlayer.tsx
components/WaveForm/WaveForm.js
icons/Line icons/Media & devices/pause.svg
icons/StemstrIcon.js
utils/common.ts

add scrubbing

---

components/NotificationView/NotificationView.tsx
ndk/hooks/useNotifications.tsx
ndk/utils.tsx

- Fix zap notification rendering
- Add client tag to zap requests
- Filter zap notifications by client tag

Zap notifications

---

components/BottomNavigationItem/BottomNavigationItem.styles.js
components/BottomNavigationItem/BottomNavigationItem.tsx
components/NotificationView/NotificationView.tsx
ndk/NostrNotificationsProvider.tsx
pages/_app.tsx
pages/notifications.tsx

make notifications a background process

Notifications provider

---

components/NoteHeader/NoteHeader.js

If no display name, name is moved to the left and displayed without an @ symbol.

update note name display

---

components/PostSheet/PostSheet.tsx

require file or comment in order to post

---

components/BottomNavigation/BottomNavigation.tsx
utils/common.ts

resolves https://github.com/stemstr/Client/issues/162

add 48px to bottom padding of navbar for pwa

---

components/PostSheet/PostSheet.tsx
icons/StemstrIcon.js

Reply sheet

---

components/BottomNavigation/BottomNavigation.tsx
components/Feed/Feed.tsx
constants/styles.ts
ndk/hooks/useFooterHeight.tsx

@rockymedure requested to reduce this to 32px.

update navbar bottom padding to 32px for PWA

---

components/PostSheet/PostSheet.tsx
utils/common.ts

resolves https://github.com/stemstr/Client/issues/171

add 48px to bottom of comment sheet

---

components/Drawer/Drawer.tsx
components/Drawer/DrawerHandle.tsx
components/PostSheet/PostSheet.tsx
components/ZapWizard/CustomAmountDrawer.tsx
components/ZapWizard/InvoiceDrawer.tsx
components/ZapWizard/ZapDrawer.tsx
components/ZapWizard/ZapDrawerHandle.tsx
components/ZapWizard/ZapOptionsDrawer.tsx
components/ZapWizard/ZapWizardProvider.tsx

resolves https://github.com/stemstr/Client/issues/166

Add handle to share sheet

---

components/NoteAction/NoteActionRepost.tsx
components/NoteActionRow/NoteActionRow.tsx
store/Notes.ts

add repost counts

---

components/DiscoverFeed/DiscoverFeed.tsx
components/Feed/Feed.tsx
components/Feed/NewEventsPill.styles.ts
components/Feed/NewEventsPill.tsx

Just loading a hard coded event for now as a POC to see if we want to do this or not. I can swap in a real subscription if this POC gets the thumbs up from everyone.
https://github.com/stemstr/Client/assets/3655410/866ef5ed-00c7-4445-88ff-33a30caed76c

new event pill

---

components/NoteContent/MentionLink.tsx
components/NoteContent/NoteContent.styles.ts
components/NoteContent/NoteContent.tsx

make links clickable in notes

---

components/Drawer/Drawer.tsx

resolves https://github.com/stemstr/Client/issues/194

improve drawer handle drag to close

---

components/NotificationView/NotificationView.tsx

fix notification card overflowing

---

components/NoteContent/NoteContent.tsx
components/Settings/SettingLogout.tsx
ndk/NostrNotificationsProvider.tsx
ndk/hooks/useFeed.tsx

clear notifications on logout

---

components/NotificationView/NotificationView.styles.js

fix heart display issue in notifications

---

components/ContactsTray/ContactsTray.tsx
components/ContactsTray/FollowersPanel.tsx
components/ProfilePage/ProfileContactsBar.tsx
pages/user/[hexOrNpub]/contacts/[tab].tsx

remove relay section temporarily

---

components/ZapWizard/ZapWizard.tsx
ndk/utils.tsx

https://github.com/stemstr/Client/assets/3655410/98758024-c07a-43ba-a03e-ad08784967b2

Display zap error notification

---

pages/_app.tsx

disable zoom on mobile

---

components/ProfileMenu/ProfileMenu.tsx
hooks/useAuth.tsx

Subscription

---

components/Feed/Feed.tsx
components/Feed/GhostFeed.tsx
ndk/NDKProvider.tsx

https://github.com/stemstr/Client/assets/3655410/f76f67f0-1e0e-4303-9831-795953dbf45b

add ghost loading feed

---

components/Feed/Feed.tsx

fixed 2 issues:
- the since filter was being inclusive when it previously wasn't inclusive
- the slide up transition screwed up the styling of the pill

fix new event pill

---

ndk/NDKProvider.tsx
ndk/utils.tsx

try to create nip-07 signer a 5 times on page load. if still failing, then log the user out and redirect to login page.

improve nip-07 login failure

---

components/NoteHeader/NoteHeader.js
components/NotificationView/NotificationView.tsx
components/ProfileLink/ProfileLink.js
components/ProfilePage/ProfilePic.tsx
ndk/hooks/useProfilePicSrc.tsx
package.json
yarn.lock

add pfp placeholders

---

ndk/NostrNotificationsProvider.tsx
ndk/hooks/useFeed.tsx

should improve performance a bit

throttle notification updates more

---

components/Fields/AboutField/AboutField.js
components/Fields/BannerSelector/BannerSelector.js
components/Fields/ProfilePicSelector/ProfilePicSelector.js
components/SignupForm/SignupForm.js

signup experience

---

components/NotificationView/NotificationView.tsx
components/NotificationsFeed/NotificationsFeed.tsx
package.json
pages/notifications.tsx
pages/thread/[noteId].tsx
yarn.lock

virtualize notifications feed

---

utils/common.ts

fix hasNotch function
